# Fly.io app configuration for a non-HTTP Discord bot with a persistent volume

app = "fight-night-discord-bot"
primary_region = "iad"        # keep this consistent with where you create the volume

# Optional env (set what you actually use)
[env]
  TZ = "America/New_York"
  # DB_FILE defaults in Dockerfile to /data/bot.db; override here if needed
  # DB_FILE = "/data/bot.db"

# Mount a Fly Volume named "data" at /data inside the VM
[mounts]
  source = "data"
  destination = "/data"

# VM sizing (keeps deploys idempotent)
# Use either a preset size OR explicit cpu/memory.
# https://fly.io/docs/launch/scale-machine/
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

# Note: No [http_service] block — this app doesn't expose HTTP.
# https://fly.io/docs/launch/volume-storage/

# Define a service to prevent the machine from being considered idle,
# and configure it to stay online.
[[services]]
  internal_port = 8080 # Port is arbitrary, as it's not exposed
  protocol = "tcp"
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
