# Fly.io app configuration for Fight Night Discord Bot

# Change this to your app name: fly apps create <name>
app = "fight-night-bot"

# Pick a close region (e.g., iad, sjc, ord, fra)
primary_region = "ord"

[build]
  # Uses Dockerfile in repo; no extra config needed

[env]
  # Default timezone and daily run time (IANA + HH:MM)
  TZ = "America/New_York"
  RUN_AT = "16:00"
  # Dockerfile defaults DB_FILE to /data/bot.db; override if desired
  # DB_FILE = "/data/bot.db"

[[mounts]]
  # Create with: fly volumes create data --size 1 --region <region>
  source = "data"
  destination = "/data"

# This app does not expose HTTP services. It runs a background bot process
# that connects outward to Discord. No [http_service] block is required.

# Secrets: set your Discord token before first deploy:
#   fly secrets set DISCORD_TOKEN=your-bot-token

# Scaling: to avoid duplicate notifications, keep a single machine/VM.
# After deploy, enforce this with:
#   fly scale count 1

